### PR TITLE
Add linter github action and husky commit checking

### PR DESCRIPTION
**Pull request by tiagoicp**
Demo:
Screenshot 2023-10-18 at 14 30 55

Screenshot 2023-10-18 at 14 41 02

Screenshot 2023-10-18 at 14 42 27

### CODE REVIEW

**Comment by tiagoicp** [comment]
@krpeacock this is last PR.

Please consider merging "update packages" first: https://github.com/dfinity/dfn-components/pull/23
Then "format fix": https://github.com/dfinity/dfn-components/pull/24

And this one adds github action checking for prettier and audit of the packages. It also adds precommit checking to warn any developer that they still need to run format before pushing.

I preferred not to add pretty-quick lib because the repo is super small and don't see yet the need to add an extra lib (and it's dependencies).

Let me know if more work is needed here.

Thanks,
Tiago

**Comment by tiagoicp** [comment]
This PR and neither of the previous PR were yet merged, although previous ones were approved.

Can you please clarify if I need to reach out to someone specific, for the PRs to be merged?

Tagging @krpeacock and @rvanasa for help 🙏 

Thanks,
TL

**Review by rvanasa — APPROVED** [review]
LGTM! Kyle (@krpeacock) is usually the person who would approve and merge these changes but has a lot of other high-priority responsibilities this week. It's also worth mentioning that we have to manually look through every line of code in the "Files Changed" tab as part of the review process, which can be a bit time-consuming for widespread formatting changes. One solution is to open PRs which are set to merge into the previous PR. 

Thanks again for the contributions!

**Comment by rvanasa** [comment]
Merged #23 and #24 to help expedite things for you. It looks like there are some wonky automatic merge conflicts, but these can be fixed by doing something like `git pull -X ours` and then re-running the formatter and `npm i`.

**Comment by tiagoicp** [comment]
Hi @rvanasa , thanks for merging the previous PR.

Have fixed conflicts in this one. Besides the added code of github action + husky, it's fixing some comma changes that for some reason didn't end up in the previous PRs. 

Those changes were all from the formatter, not mine.

Kindly merge 🙏 

PS.: also tagging @krpeacock

**Pull request merged**
